[11기_김하정] 모델링과 Django ORM 과제 제출합니다!
CEOS-Developers/django-REST-framework-2020 pull request #1
Opened 2020-04-10 06:47 UTC by Kim-Ha-Jeong

README에 간략한 소감 + 모델링 한 과정을 적었습니다!

2020-04-11 01:59 UTC, hanqyu commented on README.md
> +	부분적으로 필드가 수정되는 경우도 있지만, 만일 그 필드가 외래키로 연결되어 있으면 다른 모델을 지우고 시작해야 하더라고요ㅠ
아마 외래키 필드가 변경되면서 현재 데이터베이스의 costraint를 위반하면서 발생하는 문제일 것 같은데요, 개발 초기니까 디비는 여러번 재생성하셔도 상관없지만, migration파일 내에 `migrations.RunSQL(sql="~~") `을 선언하시고 적절한 UPDATE문을 통해 constraint를 위반하지 않도록 수정해주시는 방법이 있을 것 같습니다. 보통은 외래키를 포함해서 필드를 바꾼다고 모델을 지워야하는 상황까지 생기진 않아요! 

[Django migrations.RunSQL 독스](https://docs.djangoproject.com/en/3.0/ref/migration-operations/#runsql)

2020-04-11 03:00 UTC, hanqyu reviewed
안녕하세요! 한규주입니다.

모델을 7개나 짜오셨군요! 필요한 서비스에 맞는 모델들을 잘 설정해주신 것 같습니다. 모델링은 비즈니스 모델에 따라 관습을 따르지 않는 부분도 있고, 비효율적으로 보이는 부분들도 감수 해야 할 수도 있어서 정답은 없다는 걸 아실테니 제가 드리는 코멘트는 참고로만 봐주시면 될 것 같아요 :)

추가로 __pycache__ 파일에 대해 말씀드리자면 해당 파일은 다른 협업자와 충돌이 날 여지가 있기 때문에 `.gitignore`에 추가하셔서 커밋되지 않도록 해주시는게 좋습니다!

모델링은 항상 어려운 부분에 속하는데요, 연결관계를 변경해야하는 경우가 아니라면 나중에 손쉽게 변경할 수가 있기도 하고, 연결관계 또한 조금만 노력을 기울이면 수정할 수 있습니다. 그래서 자주 반복해서 좋은 모델링에 대한 감을 익히시되, 실제 서비스를 만들때는 지나친 고민 때문에 개발기간이 너무 늦어지는 일이 없도록 하시는게 좋은 자세라고 생각하고 있어요 :)

다소 많은 내용을 달아드렸는데 천천히 참고해보시구, 1등 PR  🥇 수고하셨어요 ㅎㅎ

2020-04-11 03:00 UTC, hanqyu commented on README.md
> +	이것 때문에 한 번 더 모델링을 다 지우고 시작했습니다ㅠ
모델을 새로 만드실 필요는 없으셨을 것 같아요!

일단 pk는 보통 auto-increment기 때문에 객체 생성하실때 인자로 넣어주셔야 할 일은 거의 없으실거구 (branch모델은 좀 달라보이지만요) 다른 필드들도 보통 객체 생성하실땐 암시적으로 인자를 positional argument로 넣어주시기 보단 keyword argument로 선언해주시는 것이 안전합니다! 안전성 말고도 객체 생성은 코드 여기저기서 쓰일텐데 그 필드 순서를 다 기억하거나 그때 그때 참조하기엔 생산성이 좀 떨어질 것 같아요.

관련 링크 첨부합니다!
[postional argument vs keyword argument](https://stackoverflow.com/questions/9450656/positional-argument-v-s-keyword-argument)

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +    branch_name = models.CharField(max_length=20, primary_key=True)
의도에 따라 다르겠지만 웬만하면 string을 pk로 쓰시지 않는게 좋습니다! default로 사용되는 id 필드(big int, auto-increment)를 사용하시는게 여러모로 좋습니다!

string을 pk로 쓰지 않아야 하는 이유에 대해서 설명드리면,
1.  indexing의 사이즈가 너무 커진다.
2. 새로 생성될때마다 indexing의 reordering이 일어날 것이므로 database의 부하가 있다. (sequential order를 유지하기위해)
3.  indexing을 쓰더라도 lookup speed에서 손해를 본다
4. admin등 해당 객체를 참조하는 url이 string이고 그 string이 한글일때 url encoding 에러의 가능성이 있다.
5. 그 string값이 변경되었을때 기존의 그 string을 사용하던 url이 무력해진다.

따라서 `primary_key=True` 를 쓰시기 보다는 `unique=True`를 쓰시는게 의도대로 구현되는 방향일 것 같아요!

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +class Theater(models.Model):
관을 설명하는 필드 이름으로는 screen이 더 나을 것 같은데 참고만 해주세요 ^^;

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +    total_theater = models.IntegerField()
IntegerField를 사용하실때 `default`값을 지정해주시지 않았으니 non-nullable인 필드가 되는데, 이런 사용은 조금 주의해주셔야 합니다! 객체 생성 시에 관의 갯수가 확정이 되어있어야 한다 (아니면 0으로 넣은 후에 나중에 update 해야 한다)는 조건이 생기는 것이라 `default=0` 혹은 `null=True` 로 설정해주시는 것이 좋을 것 같아요!

추가로 Theater의 갯수는 `theater_set.count()`를 통해 참조하시는게 더 편리하고 데이터의 정확성을 유지할 수 있어서 이 필드는 추가하지 않는 것이 더 좋을 수도 있어요. 관의 갯수가 변경될 일이 매우 적다 && 이 관의 갯수를 참조할 일이 많다면 필드 값으로 저장해두시는 것도 좋지만, 관의 갯수가 변경될때마다 이 값의 업데이트를 해줘야 해서 비효율이 조금 있어요. 

실수로 업데이트를 하지 않는 코드가 있다고 해서 데이터가 부정확해지는 것이라면 좋지 않은 모델링이 되겠죠?

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +    branch = models.ForeignKey('Branch', on_delete=models.CASCADE)
이건 필수는 아니지만 저 같은 경우는 `related_name` 을 꼭 설정해주고 있어요. 안 그렇다면 `theater_set` 이 default로 설정될 텐데, 이보다는 `related_name='theaters'`가 좀 더 가독성이 좋은 코드가 될 것 같아서 그렇습니다!

```
[X] branch.theater_set.all()
[O] branch.theaters.all()
```

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +    is_reservation = models.BooleanField(default=False)
과제의 scope가 이정도까지 다루고 있지는 않긴 하지만 보통 예약됨 아님의 경우는 시간대마다 True일수도 False일 수도 있는 데이터이기 때문에 데이터베이스에 필드로 존재하기에 좋은 데이터는 아닌 것 같아요.
```python
@property
def is_reserved(self, date, time):
    schedule = Schedule.objects.filter(schedule_date=date, schedule_time=time, branch=self.branch, theater=self.theater)
    return schedule.reservation_ticket_set.filter(seat=self).exists()
```

이렇게 설정해주신다면 객체, 시간대마다 다른 예약의 상태를 나타내기에 좋을 것 같습니다!

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +class Movie(models.Model):
이렇게 영화의 데이터를 따로 분리해두신 것 좋은 것 같아요!

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +        self.id
return 문이 빠져있어서 string 표현이 None으로 될 것 같습니다 :)

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +    schedule_time = models.TimeField()
두 컬럼은 `models.DateTimeField()`로 한번에 설정해주시는 게 유리할 것 같아요!

schdule을 시간순대로 정렬해야 할 일이 많을텐데 설정해주신 대로하면 date필드와 time를 항상 같이 사용해야할 것으로 보입니다. 거의 항상 같이 쓰일 필드라면 하나로 합쳐주는게 낫겠죠?

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +class ReservationTicket(models.Model):
이 티켓을 예약한 user 모델 참조가 추가되면 더 좋을 것으로 보여요!

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +    movie_title = models.CharField(max_length=50)
movie 객체라서 `movie_title`보다는 `title`이 redundant함을 줄일 수 있을 것 같아요!

```python
[X] movie.movie_title == '기생충'
[O] movie.title == '기생충'
```

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +    theater_no = models.CharField(max_length=10, primary_key=True)
pk는 unique 값이기 때문에 theater_no를 pk로 설정해주시면 충돌이 날 여지가 많을 것 같습니다!
예를 들어 CGV 용산과 CGV 동대문의 1관은 서로 다른 개념이기 때문에 서로 병존할 수 있도록 해주셔야 할 것 같아요!

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +        self.id
그리고 `def __str__(self)`를 설정해주는 이유는 콘솔에서 객체를 표현할 때, 어드민에서 객체가 표현될 때라서 등 사실 대부분의 유저들에게는 노출될 일이 적긴 하지만, 그냥 id를 뱉는 것 보다는 객체를 표현할 수 있을 만한 속성으로 표현되는게 더 개발생산성에는 좋을 것 같습니다! 

아래 예시는 투머치일 순 있긴 한데 설정해두면 언젠가는 도움이 되는 예시라고 생각해주세요.
```
def __str__(self):
    return f'{self.movie.movie_title} ({branch.branch_name} / {theater.theater_no}관) - {self.schedule.schedule_date, self.schedule.schedule_time}'
```

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +class ReservationTicket(models.Model):
그리고 ReservationTicket의 필드 선언에 있어서 고민을 해볼 수 있는 여지가 있는데,
movie, branch, theater는 schedule에 이미 있는 정보라서 또 연결해두실 필요는 없을 것 같아요.
둘의 데이터가 다른 경우에 충돌이 날 여지도 있어서 최대한 연결관계는 단순하게 두시는 게 좋아요. (ex. Schdule은 1관이지만 ReservationTicket은 2관인 경우?)

하지만 ReservationTicket을 직접 참조해야 하는 경우가 많은 경우에는 code의 단순함, 참조 속도의 유리함등의 이유로 추가로 연결해두시는 것도 방법이라서 이건 고민해야 하는 영역으로 남겨둘게요!

2020-04-11 03:00 UTC, hanqyu commented on api/models.py
> +class Member(models.Model):
Member 모델이 이 프로젝트의 User모델로 해당되는 것 같아서 
장고에서 User모델을 새로 만드실땐 조금 복잡한 로직을 거쳐야 해요! 

아래 두 링크 참조해드릴테니 확인해보세요!
(읽어보시면 아시겠지만 워낙 귀찮은 일이 아니라 웬만하면 기본 user model을 쓰시거나 AbstractUserModel을 상속하셔서 조금만 변경하시는게 낫습니다 ㅎㅎ)

[AbstractUserModel 상속하는 법](https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#abstractbaseuser)
[비즈니스 로직마다 알맞은 User Model을 만드는 법](https://simpleisbetterthancomplex.com/tutorial/2018/01/18/how-to-implement-multiple-user-types-with-django.html)

2020-04-11 12:25 UTC, qqri reviewed
안녕하세요!!! 김규리입니다. 😆

1등으로 과제 제출해주셨네요!!! 축하드립니다~~!!!!🎉🎁
저는 모델링에 답은 없다고 생각해요! 저의 리뷰는 하나의 의견일 뿐이고 제가 완벽한 이해가 안됐을 수 있으니 참고만해주세용 ㅎㅎㅎ😁😁

정말 잘하신 것 같아요! 수업도 듣는 처음 중이시라고 하셨는데 전반적으로 각자 역할대로 잘 나뉘어 있고 각 테이블의 역할도 확실하고 1:N / 1:1과 같은 관계설정도 잘하신 것 같습니다!! 👍👍  

고생많으셨습니다!!! 👏👏👏

2020-04-11 12:25 UTC, qqri commented on api_server/settings.py
> +
필수 과제는 아니었지만 SECRET_KEY도  secrets.json에 
넣어 주시면 좋을 것 같아요! 
SECRET_KEY도 중요한 정보 이기 때문에 따로 보관해두는게 좋거든요! 
Databases 정보 넣는것과 동일한 방법 으로 넣어주시면 됩니다.

secrets.json 에 
"SECRET_KEY": "##your secret key##" ,  이렇게  추가하고 

setting.py에
SECRET_KEY = secrets['SECRET_KEY']

해주시면 된답니다! 
참고링크 : [django secrets 관리하기](https://lhy.kr/django-secrets)

2020-04-11 12:25 UTC, qqri commented on api/models.py
> +class Member(models.Model):
기본 User 모델로 리팩토링 하는것이 좋을 것 같습니다! 
user model의 내장된 필드들이 필요하지 않을 수도 있고, 내장되지 않은 필드들이 필요할 수도 있어서요! 나중에 프로젝트 중간 단계에 커스텀하려 하면 프로젝트가 장고와 내부적을 연결되있어서 전환이 힘들 수 있습니다. 그래서 시작 단계에서 커스텀하여 개발하는 것을 추천드립니다!! 

참고로 AbstractBaseUser 슈퍼클래스는 pw, last_login, is_active와 관련한 필드와 패스워드 관련 함수를 제공해줍니다! 다른 필요한 필드들은 직접 커스텀 해주시면 됩니다. (user 만들때 사용하면 더 편리하겠죵?)
 
Custom user model 만드는 방법  관련한 링크 올리고 가겠습니다!! (위에 분이 올려주신 내용이 더 자세합니다.! ) 

[django커스텀유저](https://medium.com/@hckcksrl/django-%EC%BB%A4%EC%8A%A4%ED%85%80-%EC%9C%A0%EC%A0%80-%EB%AA%A8%EB%8D%B8-custom-user-model-b8487c0d150)
[django 유저 공식문서](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project)

2020-04-11 12:25 UTC, qqri commented on api/models.py
> +class Branch(models.Model):
혹시 branch 모델이 무슨테이블인지 알려주실수 있을까요??
지역 영화관 을 의미하는건가요??! 이름만 봐서는 바로 이해가 안가서요..!

2020-04-11 12:25 UTC, qqri commented on api/models.py
> +class Pay(models.Model):
pay는 단순히 결제만 의미하는 모델인가요!?
결제 내역과 관련한 전반적인 내용을 담은 것이라면 one to one 관계보다는 one to many 관계가 맞을것 같아요! 유저 한명이 여러개를 예매했을 수도 있기때문입니다!!

2020-04-11 12:30 UTC, qqri commented on api/models.py
> +class Seat(models.Model):
좌석과 영화관을 모델 나누신것 잘하신것 같습니다!
각각의 역할을 잘 나타내는 것 같아서 좋아요!!! 👍

2020-04-11 15:11 UTC, Kim-Ha-Jeong commented on api/models.py
> +class Branch(models.Model):
지역 영화관이라기 보다는 저는 '신촌점' 같은 지점 생각했어요!

2020-04-13 06:49 UTC, hanqyu requested changes
잘해주셨어요! 
테이블 간 관계도 좀 더 깔끔하게 되었고 property 사용도 좋은 시도 해주신 것 같아요.

다만 migrations 파일은 한번이라도 migrate한건 웬만해선 수정하지 않는게 좋은 습관이에요.
보통 협업을 하면 migrations 파일을 공유하게 되는데 다른 멤버의 로컬 디비나 서버에 있는 production 디비는 이미 migrated된 파일을 참조하고 있을 거라서, 모델의 수정사항이 있으면 새로운 migrations 파일을 만드셔서 대응해주시는게 좋습니다!

말씀드린 것만 반영하면 좋은 프로젝트가 될 것 같습니다.
고생해주셨구, 조금만 더 수정해주셔서 뵈어요 👍

2020-04-13 06:49 UTC, hanqyu commented on api/models.py
> +    def is_reserved(self, time):
잘해주셨어요! 쿼리는 이렇게 짜주시면 될 것 같구요, 다만 객체의 property는 callable하지 않기 때문에 @property에 인자를 설정하시는 방법보다는 method로 적용하셔야 할 것 같아요!

제가 시간대를 dynamic하게 고려해야하는걸 생각못하고 property를 말씀드렸네요. 😭

2020-04-13 06:49 UTC, hanqyu commented on api/models.py
> +    member = models.ForeignKey('User', on_delete=models.CASCADE, related_name='member')
이미 User모델을 만드셨기 때문에 `member` 라는 필드명보다는 `user`가 혼돈의 여지가 적을 것 같습니다!
기존 User모델과 충돌을 고려하셔서 그런 걸 수도 있지만 models.py에 존재하는 User 클래스는 하정님이 선언하신 User모델 밖에 없기 때문에 괜찮을 거에요.

그리고 related_name은 User에서 reservation_ticket을 찾을 때 쓰는 거라서 member보다는 reservation_tickets로 수정해주시는게 맞을 것 같아요!

```python
[X] user.members  # ReservationTicket의 쿼리셋?
[O] user.reservation_tickets
```

django 내에서는 보통은 1:N 관계에서 1이 N을 related 되었다고 부릅니다! 그래서 user에서 related된 객체는 ReservationTicket이고 이들을 부르는(`related_name`)은 `reservation_tickets`으로 부르는게 맞아요 :)

2020-04-14 10:07 UTC, Kim-Ha-Jeong commented on api/models.py
> +    def is_reserved(self, time):
@property를 단순히 지우면 model에 반영이 안되나요? 코드 지우긴 했는데 그냥 내비둬도 되는 건가요?

2020-04-14 12:29 UTC, hanqyu commented on api/models.py
> +    def is_reserved(self, time):
넵넵 디비에는 반영되는 값이 아니라 migration 파일에 반영하지 않으셔도 괜찮습니다!

2020-04-14 12:33 UTC, hanqyu requested changes

2020-04-14 12:33 UTC, hanqyu commented on api/models.py
> +    user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='user')
리뷰 반영 감사드려요! 나머지 related_field를 사용하는 필드도 동일하게 수정해주시면 머지해드리겠습니다..!

2020-04-15 16:09 UTC, hanqyu commented
@Kim-Ha-Jeong related_name='reservation_ticktes' 이 부분 오타나셨는데 😢 그거랑 Schedule의 related_name을 `schedules` 로 변경해주시는게 더 좋을 것이라는 것 말고는 좋습니다!

머지해드릴테니 추후에 수정하시는게 더 나을 것 같네요. 수고하셨습니다 :+1:

2020-04-15 16:09 UTC, merged