[11기_김태은] Django 모델링 미션 제출합니다
CEOS-Developers/django-REST-framework-2020 pull request #3
Opened 2020-04-12 07:39 UTC by code4human

2020-04-13 09:33 UTC, workromancer approved these changes
안녕하세요 태은님, 저는 코멘트를 남기게 된 권민철이라고 합니다.
README 작성도, 적절하게 uk, pk 사용하시면서 모델 작성도 잘 해주셔서 딱히 코멘트를 남길 포인트가 없네요. 🤣
이번 미션 고생 많으셨어요. 다음 미션도 기대할께요~

2020-04-13 09:33 UTC, TheDevLuffy commented on README.md
> +DB sql 문법과 Django ORM 문법이 달라서 원하는 논리를 풀어내는 데 시간이 걸렸습니다. <br>
이걸 느끼셨다니 멋지네요. 👍
Django ORM 의 ORM 이 Object Relation Mapping 의 약자죠?
객체지향 진영에서 객체지향적 관점으로 DB 를 설계하기 위한 도구로 만들어진 것이기 때문에 양쪽(데이터지향, 객체지향) 관점을 동일하게 풀어내는 것이 어려운 것은 당연한 것이겠죠?
객체지향 관점으로 데이터베이스를 다루기 위해 ORM 이 만들어진 만큼 객체 관점에서 설계하는 것이 좋을 것 같아요~

2020-04-13 09:33 UTC, TheDevLuffy commented on api/migrations/0001_initial.py
> +class Migration(migrations.Migration):
👍

2020-04-13 12:03 UTC, heejoe0222 commented on README.md
> +![2](./git_image/2.jpg "2")
이미지 파일은 잘 올라와있는데 `.jpg` 확장자가 `.JPG` 대문자로 되어있어서 이미지가 안 뜨는것 같네요! 대문자로 바꿔주시면 이미지 잘 뜰 것 같습니다😊

2020-04-13 12:03 UTC, heejoe0222 commented on README.md
> +쇼핑몰에서 가장 핵심적인 `'유저', '상품', '주문', '배송', '제조업체', '리뷰' ` 테이블을 설계했습니다. <br>
실제 서비스와 유사하게 모델을 5개+USER 확장 모델까지 6개나 해주셨네요😁👍👍

2020-04-13 12:03 UTC, heejoe0222 commented on README.md
> +django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xEC\\xA0\\x9C\\xEC\\xA1\\xB0...' for column 'name' at row 1") <br>
아마도 한글 삽입할 때 기존 설정이 utf-8이 아니어서 발생하는 mysql 인코딩 문제 같네요🤣 도움될지는 모르겠지만 아래 참고링크 몇 개 첨부합니다!

[MySQL 1366, "Incorrect string value:" 오류 해결](https://jyspw.tistory.com/24)
[파이썬 MYSQL Incorrect string value 에러 조치하기](https://itissmart.tistory.com/56)

2020-04-13 12:03 UTC, heejoe0222 commented on README.md
> +![ERD_1](./git_image/ERD_1.jpg "ERD_1")
E-R 다이어그램까지 그려주시다니 너무 멋져요.🙈🧡 관계가 한눈에 파악되네요! 1:1, 1:N, N:M 관계를 상황에 맞게 잘 설정해주신 것 같아요~

2020-04-13 12:03 UTC, heejoe0222 commented on README.md
> +django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xEC\\xA0\\x9C\\xEC\\xA1\\xB0...' for column 'name' at row 1") <br>
해당 에러는 당장은 고치기 어려울 수 있으니 일단은 해보시되 시간이 오래 걸릴 것 같으면 일단 나머지 리뷰들 반영하시고 슬랙에 댓글 또는 답글 남겨주세요! Merge 해 드리겠습니다🙌

2020-04-13 12:03 UTC, heejoe0222 commented on api/models.py
>      many = models.IntegerField('주문수량')
주문수량이니까 Order 객체 내에 있는 필드명은 num 또는 quantity으로 나타내면 명확하게 다가올 것 같네요!

2020-04-13 12:03 UTC, heejoe0222 commented on api/models.py
>      supply_vol = models.IntegerField('공급량')
공급량은 어떻게 사용되는 필드인지 궁금하네요! 재고량과 따로 둔 이유가 있을까요??
(해당 상품이 한 번에 몇 개씩 공급되는지 알려주는 값인지?)

2020-04-13 12:03 UTC, heejoe0222 commented on api/models.py
>      pro_num = models.ManyToManyField(
`pro_num`은 구매한 수량? 처럼 보여서 `구매한 상품`이라는 의미를 표현할 수 있는 이름으로 바꾸면 좋을 것 같아요!

2020-04-13 12:03 UTC, heejoe0222 commented on api/models.py
>      pro_num = models.ManyToManyField(
Product에 User들이 있을수도 있지만 User에 Product들이 있는 게 더 명확해보이네요!  `ManyToManyField`를 적절한 위치에 적절하게 잘 사용하신 것 같아요😎👍

2020-04-13 12:03 UTC, heejoe0222 commented on api/models.py
> +    location = models.CharField(_('user address'), max_length=100)
주소를 나타내기엔 `address`가 더 적절한 필드명일 것 같네요!

2020-04-13 12:03 UTC, heejoe0222 commented on api/models.py
> +    class Meta:
Meta 옵션까지 설정해주신 거 너무 디테일하고 좋아요😍

2020-04-13 12:03 UTC, heejoe0222 commented on api/models.py
> +    destination = models.CharField(_('destination'), max_length=100)
배송지는 기본 사용자의 주소 외의 장소도 지정할 수 있으므로 `MyUser`의 `location`을 참조하기보단 이렇게 새로 필드를 지정해주는 게 적절한 것 같네요!

2020-04-13 12:03 UTC, heejoe0222 commented on api/models.py
>      phone = models.CharField(_('phone number'), max_length=20)
핸드폰 번호는 11자리 고정이라 max_length를 11자리로 지정해주는 것도 나쁘지 않을 것 같아요~ (대한민국 서비스인 경우)

2020-04-13 12:03 UTC, heejoe0222 commented on api/models.py
> +    transport = models.IntegerField('운송장번호')
운송장번호도 핸드폰번호처럼 개수/수량보다는 정해진 길이의 번호 느낌이라 `CharField`가 적절하지 않을까 싶어요!

2020-04-13 12:03 UTC, heejoe0222 commented on api/models.py
> +    state = models.CharField('배송상태', max_length=20, choices=STATE, default='preparing')
배송 상태를 `choices 옵션` 사용해서 아주 잘 나타내주셨어요! 🤩

2020-04-13 12:10 UTC, heejoe0222 commented
안녕하세요, 태은님! 리뷰어 최희조입니다😁🖐

태은 님의 모델링에 리뷰를 남기게 되어 너무 영광이예요~!! 기대 이상으로 너무 꼼꼼하고 디테일하게
잘 짜주셔서 감동했어요💖모델 개수부터 필드, Meta 옵션, 다이어그램까지 과제하면서 태은 님이 어떻게 고민해주셨는지가 너무 잘 드러나서 멋있었네요🤩✒

저는 철저히 관찰자 입장으로 보고 리뷰를 남긴거라 참고할 부분은 참고해주시고, 태은 님이 생각하기에 이 부분은 그냥 둬도 괜찮을 꺼 같은데? 라고 생각하시는 부분은 그냥 두셔도 되어요!!
이번 과제도 너무 수고 많으셨구요, 리뷰 반영하시고 슬랙에 답글 남겨주세요😄 기다리겠습니다~

2020-04-13 12:18 UTC, heejoe0222 requested changes
@code4human 두 명 모두 리뷰 올렸습니다! 확인해주시구 반영해서 다시 push 해주세요~🥰

2020-04-15 15:57 UTC, heejoe0222 requested changes
안녕하세요, 태은 님! 리뷰 반영해주신 부분 잘 봤습니다😊💕

리뷰 확인하다가 제가 저번에 미처 발견하지 못한 부분들과 아직 반영 못한 부분이 몇 군데 보여서
다시 리뷰 요청 드려요! 이번에 말씀 드리는 부분만 잘 반영해주시면 바로 merge해드릴게요~😎
조금만 더 수고해주세요! 화이팅😤😤👏

p.s 혹시 궁금한 점이나 납득 안 가는 부분 추가로 생기시면 언제든지 슬랙 qna 게시판이나 깃헙 댓글로 여쭤봐주세요!! 질문은 언제든지 환영이에요🤗🙌

2020-04-15 15:57 UTC, heejoe0222 commented on api/models.py
> +    location = models.CharField('주소', max_length=100)
User의 주소를 의미하는 필드명으로 `location`보단 `address`가 적절할 것 같아요!

2020-04-15 15:57 UTC, heejoe0222 commented on api/models.py
> +        'Manufacturer',
ForeignKey 1:N 관계에서 1에 대해 N을 어떻게 표현할지 직관적으로 나타낼 수 있도록 `related_name` 써주시면 좋습니다! `related_name`을 명시하지 않고 ORM 쿼리 사용 시 장고가 자동으로 `_set`을 붙여서 `Manufacturer.product_set.all()`으로 사용할 수 있긴 하지만 `related_name='products'`로 설정해주시면 좀 더 깔끔하고 직관적으로 `Manufacturer.prouducts.all()` 같이 사용하실 수 있답니다! 자세한 설명은 [링크](https://fabl1106.github.io/django/2019/05/27/Django-26.-%EC%9E%A5%EA%B3%A0-related_name-%EC%84%A4%EC%A0%95%EB%B0%A9%EB%B2%95.html) 참조해주세요.

필수는 아니지만 작성하는 습관 들이시면 좋아요~ (저번에 알려드리는 걸 까먹어서 이제 말씀드려요ㅠㅠ)

2020-04-15 15:57 UTC, heejoe0222 commented on api/models.py
> +    pro_num = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='상품번호')
다대다 관계에서도 `related_name` 써주세요! 특정 User의 모든 Order, 특정 Product의 모든 Order를 알아야할 때 `order_set`보다는 `orders`가 직관적이고 좋을 것 같아요😋

2020-04-15 15:57 UTC, heejoe0222 commented on api/models.py
> +        # related_name='myusers',
여기의 `related_name`은 Product에 대해서 구매한 모든 유저들을 조회할 때 쓰일 수 있으니 `related_name='purchased_users'` 정도가 어떨까 싶네요! (이건 참고 정도로만 보시고 원하는 거 쓰세요🥺)

2020-04-15 15:57 UTC, heejoe0222 commented on api/models.py
> +    order = models.ForeignKey('Order', on_delete=models.CASCADE, verbose_name='주문식별')
이 부분도 저번엔 발견 못했던 부분인데 보여서 코멘트 남겨요! (여긴 당장 수정해주실 필요는 없고 참고해주세요~)
Order에 대해서 Delivery는 하나 진행되기 때문에 1:N관계보다는 1:1 (OneToOneField)가 적절해보입니다.
겉으로는 큰 차이가 없긴 하지만 역관계 조회시(order->delivery) 무조건 `_set` 을 사용해야하고 Order에 대한 delivery가 하나 뿐이라도 무조건 queryset으로 반환된다는 단점이 있어요ㅜ

둘의 차이에 대한 자세한 내용은 [이곳](https://whatisthenext.tistory.com/118)을 참조해주세요!

2020-04-15 15:57 UTC, heejoe0222 commented on api/models.py
> +    transport = models.IntegerField('운송장번호')
이 부분은 수정을 하는 게 적절해보입니다! 운송장번호는 0으로도 시작 가능한 특정 길이의 문자열 숫자일 가능성이 높으니까요🙂

2020-04-15 15:57 UTC, heejoe0222 commented on api/models.py
> +    order = models.ForeignKey('Order', on_delete=models.CASCADE, verbose_name='주문식별')
이 부분도 동일하게 `related_name`을 설정해주면 좋겠죠?

2020-04-15 15:57 UTC, heejoe0222 commented on api_server/secrets.json
> +{
이런 `secrets.json` 파일이 올라와 버렸네요ㅠ 다음부터는 꼭 올리시기 전에 `.gitignore`가 제대로 적용되는지 확인하고 올리시면 좋을 것 같아요! 프로젝트 진행 도중 `.gitignore`를 추가하게 된 경우에는 아래 코드를 적용해주세요.
```
git rm -r --cached .
git add .
git commit -m "Apply .gitignore"
```
pycharm을 사용하신다면 [github](https://dev.plusblog.co.kr/35)과 연동해서 add, commit, push, .gitignore 등을 직관적으로 편리하게 이용하실 수 있으니 한 번 이용해보세요!😁

2020-04-16 10:32 UTC, merged